erlagn :)
superwhiskers/question pull request #34
Opened 2021-01-21 19:11 UTC by monarrk

why do I keep making these

2021-01-22 00:20 UTC, superwhiskers requested changes
please make the changes outlined in this review. i will approve and merge once done

2021-01-22 00:20 UTC, superwhiskers commented on erlang/question.erl
> +question(Prompt) ->
there needs to be a comment here stating `implementation of the question function in erlang`

2021-01-22 00:20 UTC, superwhiskers commented on erlang/question.erl
> +    A = question("Foo", ["Bar", "Baz"]),
for consistency, `Foo`, `Bar`, and `Baz` should be lowercase

2021-01-22 00:20 UTC, superwhiskers commented on erlang/question.erl
> +    io:format("~s~n", [B]).
remove this line and the two above it for consistency with other implementations

2021-03-25 21:42 UTC, superwhiskers commented
@Brecert has already implemented one, it seems

2021-03-25 21:42 UTC, closed without merging

2021-03-25 22:07 UTC, monarrk commented
yeah